### PR TITLE
Try to set by default the current location href as the content-url for offline mode.

### PR DESCRIPTION
**Pull request by bcolucci**
Add default settings into addSettings function.
Try to set the content-url with the location.href variable.
Add an IDE area into the .gitignore with .idea/ ignore pattern.
Add a comment into the demo/index.html file to indicate that wa can now ommit the content-url setting.

### CODE REVIEW

**Comment by TalAter** [comment]
Thanks for the help @bcolucci 

I was looking into this while working on v0.2.0, and trying to figure out the whole default settings situation.

Unfortunately, I think this commit as it is right now would break the ability to pass static `content` to UpUp.

For example:
````javascript
UpUp.start(
  { content: 'Cannot reach site. Please check your internet connection.' }
);
````
Would show the current url instead of the content defined. This would happen because the condition at https://github.com/TalAter/UpUp/blob/5ca87d422a42586d9e766011b70b9179d7087341/src/upup.sw.js#L46 would always be true because of the default value.

**Comment by bcolucci** [comment]
What if, instead of having two different parameters for the content, we could just have the content parameter which could be an UTL or direct content ?

**Comment by TalAter** [comment]
I'll look into that when I get back home.

In the meantime, I just remembered where I put those defaults... It's been a while since I looked into them :)
https://github.com/TalAter/UpUp/blob/5ca87d422a42586d9e766011b70b9179d7087341/src/upup.js#L77

I am making some changes to how those defaults are handled in the current version.

**Comment by TalAter** [comment]
See #15

**Pull request closed without merging**
